name             'mysql-pkg'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysql-pkg'
long_description 'Installs/Configures mysql-pkg'
version          '0.1.0'

depends          'mysql'
depends          'database'
